//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelAffaren.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSet
    {
        public OrderSet()
        {
            this.SpelPerOrderSet = new HashSet<SpelPerOrderSet>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string Kommentar { get; set; }
        public int PersonerId { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual PersonerSet PersonerSet { get; set; }
        public virtual ICollection<SpelPerOrderSet> SpelPerOrderSet { get; set; }
    }
}
