//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelAffaren.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonerSet
    {
        public PersonerSet()
        {
            this.OrderSet = new HashSet<OrderSet>();
        }
    
        public int Id { get; set; }
        public string Förnamn { get; set; }
        public string Efternamn { get; set; }
        public string LogOnEmail { get; set; }
        public string Lösenord { get; set; }
        public bool AdminStatus { get; set; }
    
        public virtual ICollection<OrderSet> OrderSet { get; set; }
    }
}
