//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelAffaren.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduktSet
    {
        public ProduktSet()
        {
            this.SpelPerOrderSet = new HashSet<SpelPerOrderSet>();
            this.KonsolSet = new HashSet<KonsolSet>();
            this.GenreSet = new HashSet<GenreSet>();
        }
    
        public int Id { get; set; }
        public string Namn { get; set; }
        public int KonsolId { get; set; }
        public string Beskrivning { get; set; }
        public int Utgivningsår { get; set; }
        public int GenreId { get; set; }
        public int UtgivareId { get; set; }
        public double Betyg { get; set; }
        public double Pris { get; set; }
        public int Beställningar { get; set; }
        public bool Multiplayer { get; set; }
        public bool Singleplayer { get; set; }
    
        public virtual ICollection<SpelPerOrderSet> SpelPerOrderSet { get; set; }
        public virtual UtgivareSet UtgivareSet { get; set; }
        public virtual ICollection<KonsolSet> KonsolSet { get; set; }
        public virtual ICollection<GenreSet> GenreSet { get; set; }
    }
}
