//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelAffaren.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpelPerOrderSet
    {
        public int Antal { get; set; }
        public int SpelId { get; set; }
        public int OrderId { get; set; }
    
        public virtual OrderSet OrderSet { get; set; }
        public virtual ProduktSet ProduktSet { get; set; }
    }
}
