//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelAffaren.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpelDatabasContainer : DbContext
    {
        public SpelDatabasContainer()
            : base("name=SpelDatabasContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GenreSet> GenreSet1 { get; set; }
        public virtual DbSet<KonsolSet> KonsolSet1 { get; set; }
        public virtual DbSet<OrderSet> OrderSet1 { get; set; }
        public virtual DbSet<PersonerSet> PersonerSet1 { get; set; }
        public virtual DbSet<ProduktSet> ProduktSet1 { get; set; }
        public virtual DbSet<SpelPerOrderSet> SpelPerOrderSet1 { get; set; }
        public virtual DbSet<UtgivareSet> UtgivareSet { get; set; }
    }
}
