//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelDatabas
{
    using System;
    
    public partial class GetProductsByGenre
    {
        public int Id { get; set; }
        public string Namn { get; set; }
        public Nullable<int> KonsolId { get; set; }
        public string Beskrivning { get; set; }
        public int Utgivningsår { get; set; }
        public Nullable<int> GenreId { get; set; }
        public int UtgivareId { get; set; }
        public double Betyg { get; set; }
        public double Pris { get; set; }
        public int Beställningar { get; set; }
        public bool Multiplayer { get; set; }
        public bool Singleplayer { get; set; }
        public string Utgivare { get; set; }
        public string Konsol { get; set; }
    }
}
