//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelDatabas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.SpelPerOrder = new HashSet<SpelPerOrder>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public string Kommentar { get; set; }
        public int PersonerId { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Personer Personer { get; set; }
        public virtual ICollection<SpelPerOrder> SpelPerOrder { get; set; }
    }
}
