//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelDatabas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public Produkt()
        {
            this.Betyg = 0D;
            this.Multiplayer = false;
            this.Singleplayer = false;
            this.Konsol = new HashSet<Konsol>();
            this.Genre = new HashSet<Genre>();
            this.SpelPerOrder = new HashSet<SpelPerOrder>();
        }
    
        public int Id { get; set; }
        public string Namn { get; set; }
        public int KonsolId { get; set; }
        public string Beskrivning { get; set; }
        public int Utgivningsår { get; set; }
        public int GenreId { get; set; }
        public int Beställningar { get; set; }
        public int UtgivareId { get; set; }
        public double Betyg { get; set; }
        public double Pris { get; set; }
        public bool Multiplayer { get; set; }
        public bool Singleplayer { get; set; }
    
        public virtual ICollection<Konsol> Konsol { get; set; }
        public virtual ICollection<Genre> Genre { get; set; }
        public virtual ICollection<SpelPerOrder> SpelPerOrder { get; set; }
        public virtual Utgivare Utgivare { get; set; }
    }
}
