//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelDatabas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpelDatabasContainer : DbContext
    {
        public SpelDatabasContainer()
            : base("name=SpelDatabasContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Produkt> ProduktSet { get; set; }
        public virtual DbSet<Konsol> KonsolSet { get; set; }
        public virtual DbSet<Genre> GenreSet { get; set; }
        public virtual DbSet<Personer> PersonerSet { get; set; }
        public virtual DbSet<Order> OrderSet { get; set; }
        public virtual DbSet<SpelPerOrder> SpelPerOrderSet { get; set; }
        public virtual DbSet<Utgivare> UtgivareSet { get; set; }
    }
}
