//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpelAffaren.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProduktDto", Namespace="http://schemas.datacontract.org/2004/07/SpelAffarWCF")]
    [System.SerializableAttribute()]
    public partial class ProduktDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeskrivningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BeställningarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BetygField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SpelAffaren.ServiceReference1.GenreDto> GenresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SpelAffaren.ServiceReference1.KonsolDto> KonsolerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MultiplayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SingleplayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SpelAffaren.ServiceReference1.SpelPerOrderDto> SpelPerOrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SpelAffaren.ServiceReference1.UtgivareDto UtgivareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UtgivningsårField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beskrivning {
            get {
                return this.BeskrivningField;
            }
            set {
                if ((object.ReferenceEquals(this.BeskrivningField, value) != true)) {
                    this.BeskrivningField = value;
                    this.RaisePropertyChanged("Beskrivning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Beställningar {
            get {
                return this.BeställningarField;
            }
            set {
                if ((this.BeställningarField.Equals(value) != true)) {
                    this.BeställningarField = value;
                    this.RaisePropertyChanged("Beställningar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Betyg {
            get {
                return this.BetygField;
            }
            set {
                if ((this.BetygField.Equals(value) != true)) {
                    this.BetygField = value;
                    this.RaisePropertyChanged("Betyg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.GenreDto> Genres {
            get {
                return this.GenresField;
            }
            set {
                if ((object.ReferenceEquals(this.GenresField, value) != true)) {
                    this.GenresField = value;
                    this.RaisePropertyChanged("Genres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.KonsolDto> Konsoler {
            get {
                return this.KonsolerField;
            }
            set {
                if ((object.ReferenceEquals(this.KonsolerField, value) != true)) {
                    this.KonsolerField = value;
                    this.RaisePropertyChanged("Konsoler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Multiplayer {
            get {
                return this.MultiplayerField;
            }
            set {
                if ((this.MultiplayerField.Equals(value) != true)) {
                    this.MultiplayerField = value;
                    this.RaisePropertyChanged("Multiplayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namn {
            get {
                return this.NamnField;
            }
            set {
                if ((object.ReferenceEquals(this.NamnField, value) != true)) {
                    this.NamnField = value;
                    this.RaisePropertyChanged("Namn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Pris {
            get {
                return this.PrisField;
            }
            set {
                if ((this.PrisField.Equals(value) != true)) {
                    this.PrisField = value;
                    this.RaisePropertyChanged("Pris");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Singleplayer {
            get {
                return this.SingleplayerField;
            }
            set {
                if ((this.SingleplayerField.Equals(value) != true)) {
                    this.SingleplayerField = value;
                    this.RaisePropertyChanged("Singleplayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.SpelPerOrderDto> SpelPerOrders {
            get {
                return this.SpelPerOrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.SpelPerOrdersField, value) != true)) {
                    this.SpelPerOrdersField = value;
                    this.RaisePropertyChanged("SpelPerOrders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SpelAffaren.ServiceReference1.UtgivareDto Utgivare {
            get {
                return this.UtgivareField;
            }
            set {
                if ((object.ReferenceEquals(this.UtgivareField, value) != true)) {
                    this.UtgivareField = value;
                    this.RaisePropertyChanged("Utgivare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Utgivningsår {
            get {
                return this.UtgivningsårField;
            }
            set {
                if ((this.UtgivningsårField.Equals(value) != true)) {
                    this.UtgivningsårField = value;
                    this.RaisePropertyChanged("Utgivningsår");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UtgivareDto", Namespace="http://schemas.datacontract.org/2004/07/SpelAffarWCF")]
    [System.SerializableAttribute()]
    public partial class UtgivareDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> ProdukterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namn {
            get {
                return this.NamnField;
            }
            set {
                if ((object.ReferenceEquals(this.NamnField, value) != true)) {
                    this.NamnField = value;
                    this.RaisePropertyChanged("Namn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> Produkter {
            get {
                return this.ProdukterField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdukterField, value) != true)) {
                    this.ProdukterField = value;
                    this.RaisePropertyChanged("Produkter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenreDto", Namespace="http://schemas.datacontract.org/2004/07/SpelAffarWCF")]
    [System.SerializableAttribute()]
    public partial class GenreDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> ProdukterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namn {
            get {
                return this.NamnField;
            }
            set {
                if ((object.ReferenceEquals(this.NamnField, value) != true)) {
                    this.NamnField = value;
                    this.RaisePropertyChanged("Namn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> Produkter {
            get {
                return this.ProdukterField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdukterField, value) != true)) {
                    this.ProdukterField = value;
                    this.RaisePropertyChanged("Produkter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KonsolDto", Namespace="http://schemas.datacontract.org/2004/07/SpelAffarWCF")]
    [System.SerializableAttribute()]
    public partial class KonsolDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> ProdukterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namn {
            get {
                return this.NamnField;
            }
            set {
                if ((object.ReferenceEquals(this.NamnField, value) != true)) {
                    this.NamnField = value;
                    this.RaisePropertyChanged("Namn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> Produkter {
            get {
                return this.ProdukterField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdukterField, value) != true)) {
                    this.ProdukterField = value;
                    this.RaisePropertyChanged("Produkter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpelPerOrderDto", Namespace="http://schemas.datacontract.org/2004/07/SpelAffarWCF")]
    [System.SerializableAttribute()]
    public partial class SpelPerOrderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AntalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpelIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Antal {
            get {
                return this.AntalField;
            }
            set {
                if ((this.AntalField.Equals(value) != true)) {
                    this.AntalField = value;
                    this.RaisePropertyChanged("Antal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SpelId {
            get {
                return this.SpelIdField;
            }
            set {
                if ((this.SpelIdField.Equals(value) != true)) {
                    this.SpelIdField = value;
                    this.RaisePropertyChanged("SpelId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDto", Namespace="http://schemas.datacontract.org/2004/07/SpelAffarWCF")]
    [System.SerializableAttribute()]
    public partial class PersonDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EfternamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FörnamnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogOnEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LösenordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SpelAffaren.ServiceReference1.OrderDto> OrdrarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Efternamn {
            get {
                return this.EfternamnField;
            }
            set {
                if ((object.ReferenceEquals(this.EfternamnField, value) != true)) {
                    this.EfternamnField = value;
                    this.RaisePropertyChanged("Efternamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Förnamn {
            get {
                return this.FörnamnField;
            }
            set {
                if ((object.ReferenceEquals(this.FörnamnField, value) != true)) {
                    this.FörnamnField = value;
                    this.RaisePropertyChanged("Förnamn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogOnEmail {
            get {
                return this.LogOnEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.LogOnEmailField, value) != true)) {
                    this.LogOnEmailField = value;
                    this.RaisePropertyChanged("LogOnEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lösenord {
            get {
                return this.LösenordField;
            }
            set {
                if ((object.ReferenceEquals(this.LösenordField, value) != true)) {
                    this.LösenordField = value;
                    this.RaisePropertyChanged("Lösenord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.OrderDto> Ordrar {
            get {
                return this.OrdrarField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdrarField, value) != true)) {
                    this.OrdrarField = value;
                    this.RaisePropertyChanged("Ordrar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDto", Namespace="http://schemas.datacontract.org/2004/07/SpelAffarWCF")]
    [System.SerializableAttribute()]
    public partial class OrderDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KommentarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SpelAffaren.ServiceReference1.SpelPerOrderDto> SpelPerOrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kommentar {
            get {
                return this.KommentarField;
            }
            set {
                if ((object.ReferenceEquals(this.KommentarField, value) != true)) {
                    this.KommentarField = value;
                    this.RaisePropertyChanged("Kommentar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.SpelPerOrderDto> SpelPerOrders {
            get {
                return this.SpelPerOrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.SpelPerOrdersField, value) != true)) {
                    this.SpelPerOrdersField = value;
                    this.RaisePropertyChanged("SpelPerOrders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISpelAffarService")]
    public interface ISpelAffarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/HämtaProduktViaGenre", ReplyAction="http://tempuri.org/ISpelAffarService/HämtaProduktViaGenreResponse")]
        System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> HämtaProduktViaGenre(int genreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/HämtaProduktViaGenre", ReplyAction="http://tempuri.org/ISpelAffarService/HämtaProduktViaGenreResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto>> HämtaProduktViaGenreAsync(int genreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/HämtaProdukter", ReplyAction="http://tempuri.org/ISpelAffarService/HämtaProdukterResponse")]
        System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> HämtaProdukter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/HämtaProdukter", ReplyAction="http://tempuri.org/ISpelAffarService/HämtaProdukterResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto>> HämtaProdukterAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/HämtaProdukt", ReplyAction="http://tempuri.org/ISpelAffarService/HämtaProduktResponse")]
        SpelAffaren.ServiceReference1.ProduktDto HämtaProdukt(int produktId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/HämtaProdukt", ReplyAction="http://tempuri.org/ISpelAffarService/HämtaProduktResponse")]
        System.Threading.Tasks.Task<SpelAffaren.ServiceReference1.ProduktDto> HämtaProduktAsync(int produktId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/KollaKund", ReplyAction="http://tempuri.org/ISpelAffarService/KollaKundResponse")]
        SpelAffaren.ServiceReference1.PersonDto KollaKund(string firstName, string lastName, string logOnEmail, string lösenord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/KollaKund", ReplyAction="http://tempuri.org/ISpelAffarService/KollaKundResponse")]
        System.Threading.Tasks.Task<SpelAffaren.ServiceReference1.PersonDto> KollaKundAsync(string firstName, string lastName, string logOnEmail, string lösenord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/GetTopListGames", ReplyAction="http://tempuri.org/ISpelAffarService/GetTopListGamesResponse")]
        System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> GetTopListGames(int antal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/GetTopListGames", ReplyAction="http://tempuri.org/ISpelAffarService/GetTopListGamesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto>> GetTopListGamesAsync(int antal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/NyOrder", ReplyAction="http://tempuri.org/ISpelAffarService/NyOrderResponse")]
        SpelAffaren.ServiceReference1.OrderDto NyOrder(int kundId, System.Collections.Generic.List<int> produkter, string kommentar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/NyOrder", ReplyAction="http://tempuri.org/ISpelAffarService/NyOrderResponse")]
        System.Threading.Tasks.Task<SpelAffaren.ServiceReference1.OrderDto> NyOrderAsync(int kundId, System.Collections.Generic.List<int> produkter, string kommentar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/GetAllGenre", ReplyAction="http://tempuri.org/ISpelAffarService/GetAllGenreResponse")]
        System.Collections.Generic.List<SpelAffaren.ServiceReference1.GenreDto> GetAllGenre();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISpelAffarService/GetAllGenre", ReplyAction="http://tempuri.org/ISpelAffarService/GetAllGenreResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpelAffaren.ServiceReference1.GenreDto>> GetAllGenreAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpelAffarServiceChannel : SpelAffaren.ServiceReference1.ISpelAffarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpelAffarServiceClient : System.ServiceModel.ClientBase<SpelAffaren.ServiceReference1.ISpelAffarService>, SpelAffaren.ServiceReference1.ISpelAffarService {
        
        public SpelAffarServiceClient() {
        }
        
        public SpelAffarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpelAffarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpelAffarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpelAffarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> HämtaProduktViaGenre(int genreId) {
            return base.Channel.HämtaProduktViaGenre(genreId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto>> HämtaProduktViaGenreAsync(int genreId) {
            return base.Channel.HämtaProduktViaGenreAsync(genreId);
        }
        
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> HämtaProdukter() {
            return base.Channel.HämtaProdukter();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto>> HämtaProdukterAsync() {
            return base.Channel.HämtaProdukterAsync();
        }
        
        public SpelAffaren.ServiceReference1.ProduktDto HämtaProdukt(int produktId) {
            return base.Channel.HämtaProdukt(produktId);
        }
        
        public System.Threading.Tasks.Task<SpelAffaren.ServiceReference1.ProduktDto> HämtaProduktAsync(int produktId) {
            return base.Channel.HämtaProduktAsync(produktId);
        }
        
        public SpelAffaren.ServiceReference1.PersonDto KollaKund(string firstName, string lastName, string logOnEmail, string lösenord) {
            return base.Channel.KollaKund(firstName, lastName, logOnEmail, lösenord);
        }
        
        public System.Threading.Tasks.Task<SpelAffaren.ServiceReference1.PersonDto> KollaKundAsync(string firstName, string lastName, string logOnEmail, string lösenord) {
            return base.Channel.KollaKundAsync(firstName, lastName, logOnEmail, lösenord);
        }
        
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto> GetTopListGames(int antal) {
            return base.Channel.GetTopListGames(antal);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SpelAffaren.ServiceReference1.ProduktDto>> GetTopListGamesAsync(int antal) {
            return base.Channel.GetTopListGamesAsync(antal);
        }
        
        public SpelAffaren.ServiceReference1.OrderDto NyOrder(int kundId, System.Collections.Generic.List<int> produkter, string kommentar) {
            return base.Channel.NyOrder(kundId, produkter, kommentar);
        }
        
        public System.Threading.Tasks.Task<SpelAffaren.ServiceReference1.OrderDto> NyOrderAsync(int kundId, System.Collections.Generic.List<int> produkter, string kommentar) {
            return base.Channel.NyOrderAsync(kundId, produkter, kommentar);
        }
        
        public System.Collections.Generic.List<SpelAffaren.ServiceReference1.GenreDto> GetAllGenre() {
            return base.Channel.GetAllGenre();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SpelAffaren.ServiceReference1.GenreDto>> GetAllGenreAsync() {
            return base.Channel.GetAllGenreAsync();
        }
    }
}
